language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS

before_install:
  - pecl install swoole

script:
  - php vendor/bin/codecept run