language: php

php:
  - 5.5
  - 5.6

sudo: false

env:
  - COMPOSER_OPTS=""

matrix:
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS

before_install:
  - pecl install swoole

script:
  - php vendor/bin/codecept run